add crud for categories + add 2 custom exceptions
Pinqo-community/marketplace-backend pull request #50
Opened 2024-11-04 23:20 UTC by Pops47

NotFoundException and AlreadyExistsException added to GlobalExceptionHandler

2024-11-05 09:53 UTC, JeffreyGbeho requested changes

2024-11-05 09:53 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/controller/CategoryController.java
> +    @Autowired
Sur les nouvelles versions de Spring, on utilise le constructor injection à la place de @Autowired. Ca permet d'avoir l'immutabilité et une meilleure gestion des injections.
Ca ressemble à ça :
private final CategoryService categoryService;

puis soit avant ta class  tu utilises l'annotation Lombok @RequiredArgsConstructor (préférable dans notre cas) soit tu déclares ton constructor comme ça
public CategoryController(CategoryService categoryService) { this.categoryService = categoryService; }

2024-11-05 09:53 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/controller/CategoryController.java
Sur ton controller faut que tu ajoutes la documentation Swagger, qui se fait avec des annotations, pour qu'on puisse avoir une documentation propre de l'api

2024-11-05 09:53 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/controller/CategoryController.java
> +        return ResponseEntity.ok(categoryService.findAll());
Une bonne pratique est d'utiliser les logs pour afficher des informations que l'on pourra suivre pour débugger, surtout en prod. 
Pour ça t'as une libraire qui s'appelle Slf4j que tu peux ajouter avec l'annotation @Slf4j que tu mets au dessus de ta class puis dans tes controller, tu fais quelques choses de ce style 
try {
            log.info("POST /auth/register - START");
            // La logique de ton controller
        } finally {
            log.info("POST /auth/register - DONE");
        }

Le faire dans les controllers ça sera déjà pas mal mais on peut ajouter des logs où on veut

2024-11-05 09:53 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/entity/Category.java
> +    // Getters and setters
A la place d'écrire tes getters et setters à la main, tu peux utiliser les annotations lombok qui permet de les générer au fur et à mesure que tu rajoutes des variables dans ta class. Les annotation tu les mets au dessus de ta class. 
Les plus utiles sont : 
@Getter
@Setter
@AllArgsConstructor -> constructor avec toutes tes variables
@NoArgsConstructor -> constructor vide
@Builder -> ça permet de construire un objet sans avoir à utiliser les setters

2024-11-05 09:53 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/service/impl/CategoryService.java
> +    @Autowired
Utiliser le constructor injection (explications dans le CategoryController)

2024-11-05 09:53 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/service/impl/CategoryService.java
Une bonne pratique est d'utiliser des interfaces qui exposent les différentes méthodes que l'on va ensuite implémenter dans notre class d'implémentation. Ca permet d'avoir un couplage faible entre ton controller et ton service grâce à l'inversion de dépendances. Et ça sera plus flexible si on veut rajouter des implémentations qui ont le même comportement.

2024-11-05 09:53 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/service/impl/CategoryService.java
> +                .orElseThrow(() -> new NotFoundException("Category not found with ID: " + id));
Est ce qu'on met les messages en anglais ou en français ? Vu que l'application a pour but de servir un public français, ça peut être mieux d'utiliser le français dans les message d'erreur

2024-11-05 10:56 UTC, Pops47 commented on api/src/main/java/com/marketplace/service/impl/CategoryService.java
> +                .orElseThrow(() -> new NotFoundException("Category not found with ID: " + id));
Bonne question. Après je dira que ce message d'erreur est plutôt destiné à du debug non ? car en pratique un utilisateur n'aura jamais possibilité depuis le front de supprimer une catégorie qui n'existe pas...

2024-11-05 11:11 UTC, Pops47 commented on api/src/main/java/com/marketplace/service/impl/CategoryService.java
Ok pour le service. Est-ce que ça a un intérêt de faire une interface pour le controller aussi ou pas spécialement ?

2024-11-05 11:53 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/service/impl/CategoryService.java
T'as pas besoin de faire d'interfaces pour tes controllers parce que c'est uniquement tes servlets qui vont s'en servir. Tu n'as pas de classes qui vont faire une injection de dépendances des controllers, ce sont des entrypoints juste

2024-11-05 11:58 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/service/impl/CategoryService.java
> +                .orElseThrow(() -> new NotFoundException("Category not found with ID: " + id));
Là le message va être gérer par le GlobalExceptionHandler qui va envoyer le message dans la réponse avec un code d'erreur. Du coup le front va pouvoir utiliser ton message pour l'afficher dans un toast par exemple. Si tu veux avoir ce message uniquement pour du debug, tu dois utiliser un try/catch et l'afficher dans les logs

2024-11-05 13:16 UTC, Pops47 commented on api/src/main/java/com/marketplace/service/impl/CategoryService.java
> +                .orElseThrow(() -> new NotFoundException("Category not found with ID: " + id));
Ok je vais plutôt faire un try/catch alors, je pense qu'on aura jamais besoin d'afficher cette erreur dans le front.

2024-11-05 13:29 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/service/impl/CategoryService.java
> +                .orElseThrow(() -> new NotFoundException("Category not found with ID: " + id));
C'est quand même utile d'envoyer un message au front, ça permet à l'utilisateur de savoir pourquoi sa requête n'a pas fonctionné

2024-11-05 13:39 UTC, Pops47 commented on api/src/main/java/com/marketplace/service/impl/CategoryService.java
> +                .orElseThrow(() -> new NotFoundException("Category not found with ID: " + id));
Oui je comprends sur le principe mais en pratique je ne vois pas bien dans quel cas l'utilisateur va pouvoir tenter de supprimer une catégorie qui n'existe pas ?

2024-11-05 13:41 UTC, Pops47 commented on api/src/main/java/com/marketplace/service/impl/CategoryService.java
> +                .orElseThrow(() -> new NotFoundException("Category not found with ID: " + id));
Mais après ça me dérange pas de le laisser comme ça avec juste un message en français. J'ai juste l'impression que ça change rien vu que le message n'arrivera jamais jusqu'à un utilisateur. Le seul cas ou il pourrait s'afficher c'est pour nous quand on teste des routes depuis postman non ?

2024-11-05 14:28 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/service/impl/CategoryService.java
> +                .orElseThrow(() -> new NotFoundException("Category not found with ID: " + id));
Normalement c'est pas censé arriver. Mais t'as des cas où ça peut arriver. 
Par exemple pour le delete si on est plusieurs à pouvoir supprimer un élément. Si t'as le premier qui le supprime mais que les données sont pas en temps réel et que le deuxième veut supprimer, il aura une erreur. Donc c'est pas mal qui sache pourquoi.
Pour le get by id aussi ça peut arriver que le front est une erreur d'intégration et tente d'accéder à un élément qui n'existe pas ou peut être que l'élément vient tout juste d'être supprimé

2024-11-05 14:49 UTC, Pops47 commented on api/src/main/java/com/marketplace/service/impl/CategoryService.java
> +                .orElseThrow(() -> new NotFoundException("Category not found with ID: " + id));
Ok ça marche ! Je change le texte alors !

2024-11-05 14:55 UTC, Pops47 commented on api/src/main/java/com/marketplace/controller/CategoryController.java
Il existe des conventions particulières pour ça ? J'ai rajouté des annotations mais je sais pas trop jusqu'où je dois aller. Est-ce qu'il faut des examples de réponses réalistes pour chaque endpoint ou bien la forme de la réponse suffit ?

2024-11-05 15:09 UTC, Pops47 commented on api/src/main/java/com/marketplace/controller/CategoryController.java
> +        return ResponseEntity.ok(categoryService.findAll());
J'ai rajouté dans le controller, je peux en mettre aussi dans le service si tu penses que c'est mieux (perso j'ai pas trop de recul pour savoir si ça peut être utile)

2024-11-05 17:12 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/controller/CategoryController.java
> +        return ResponseEntity.ok(categoryService.findAll());
Dans le controller c'est déjà bien, ça nous permettra de savoir quelles routes peuvent avoir des soucis

2024-11-05 17:15 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/controller/CategoryController.java
Sur ça, j'ai pas trop d'expériences donc je peux dire les bonnes pratiques dessus. Mais je pense décrire le rôle du controller, à quoi sert chaque route, les retours possible si possible et les paramètres. Qu'est ce que tu en penses ?

2024-11-06 11:32 UTC, JeffreyGbeho requested changes

2024-11-06 11:32 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/controller/CategoryController.java
> +    public ResponseEntity<Category> createCategory(@RequestBody Category category) {
J'avais zappé ça, je viens de m'en apercevoir en faisant la code review de Lisa. Mais on évite d'utiliser les entity pour récupérer les informations des requêtes parce que ça expose tous les champs de l'entity qui peut causer des problèmes de sécurité. A la place on utilise des class DTO qui vont exposer uniquement les champs voulu pour la requête et sur ton DTO tu vas ajouter les règles de validations.
Si t'as besoin de plus d'explications, n'hésites à pas me dire c'est peu long à écrire en commentaire

2024-11-06 11:32 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/controller/CategoryController.java
> +            return ResponseEntity.status(HttpStatus.CREATED).body(categoryService.save(category));
Et du coup on évite aussi de renvoyer les entities en réponse pour une question de sécurité. On voudrait pas envoyer des informations sensibles que l'entité pourrait avoir (surtout avec les relations). A la place on fait une class DTO et pour se faciliter la vie on utiliser des mappers avec la dépendance mapstruct pour faire convertir l'entity dans le format de la nouvelle class.
Même chose si t'as besoin d'explications, dis moi

2024-11-08 16:53 UTC, Pops47 commented on api/src/main/java/com/marketplace/controller/CategoryController.java
Ca me va, j'ai juste mis des examples réalistes pour les body et j'ai laissé les structures des réponses avec juste les dto sans examples. Pour le reste ya tout normalement.

2024-11-18 10:51 UTC, Lisadev84 reviewed
Testé sur postman et Swagger. Fonctionnalité opérationnelle. Juste une suggestion sur la case sensitive pour la création des catégories. Actuellement, une catégorie nommée Volailles ou volailles sont 2 catégories distinctes et passent à la création.

2024-11-18 10:51 UTC, Lisadev84 commented on api/src/main/java/com/marketplace/repository/CategoryRepository.java
> +    boolean existsByName(String name);
peut-être envisager par la suite le case sensitive

2024-11-20 17:26 UTC, JeffreyGbeho reviewed
Il manque juste les tests unitaires

2024-12-11 22:22 UTC, JeffreyGbeho approved these changes

2024-12-12 16:35 UTC, Lisadev84 reviewed
Toutes les méthodes controller ne nécessitant pas d'authentification ou de rôles spécifiques ont été testé avec swagger et sont ok, messages d'erreur en cas de non autorisation reçus. Les Tests sont ok aussi. Besoin d'explication sur l'authentification pour tester les méthodes les nécessitant.

2024-12-12 16:35 UTC, Lisadev84 commented on api/src/main/resources/application.yml
J'ai ces avertissement, sans doute un conflit de configuration ou de version : 
Cannot resolve configuration property 'springdoc.api-docs.default-property-example'
Cannot resolve configuration property 'springdoc.api-docs.default-response-example'
Cannot resolve configuration property 'springdoc.model-converters.enabled'

2024-12-12 16:35 UTC, Lisadev84 commented on api/src/main/resources/application.yml
> +  api-docs:
Je n'ai pas utilisé ces propriétés car elle sont obsolètes à partir de la version 2.x 
cf. crud-produits

2024-12-15 17:21 UTC, Lisadev84 approved these changes
Tout est ok

2024-12-20 22:32 UTC, merged