22 crud produits
Pinqo-community/marketplace-backend pull request #52
Opened 2024-11-05 21:33 UTC by Lisadev84

- Implémentation des fichiers relatifs au Crud produits : classe, repository, service, serviceImpl.
- A ajouter  dans SecurityConfig  API_URLS_WHITELIST pour tester:   "/products/**"

**Modifications apportées :** 
- Ajustement de compose.yml, Dokerfile.dev  back-end(fix conflits et verrouilage de fichiers liés au WSL, ajout d'un container pour les tests )
- ProductDTO 
- Ajout de règles pour l'affichage des produits disponibles
- Ajout des règles pour quantité min et max du stock produit
- Gestion des erreurs
- Tests unitaires de ProductServiceImpl
- Tests unitaires  de ProductController
**Correctif** : 
- Méthode DeleteProduct du service et son test unitaire
- Restructuration de l'entité product : suppression de minQuantité et modification de la propriété MaxQuantity
- Ajustement du service et des tests
- Suppression de la validation OnCreate
- Ajout des tests pour le endpoint status

2024-11-06 11:41 UTC, JeffreyGbeho requested changes

2024-11-06 11:41 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/configuration/SecurityConfig.java
> +            "/test",
Penser à enlever pour la PR. Une bonne alternative est de mettre dans la description de PR les réglages à faire pour pouvoir test

2024-11-06 11:41 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/controller/ProductController.java
Ajouter la documentation swagger sur ton controller avec les annotations @Tag, @Operations, @ResponseAnswers et @Parameters

2024-11-06 11:41 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/controller/ProductController.java
> +    @Autowired
Avec les nouvelles versions de spring, on utilise plutôt l'injection par constructor qu'avec @Autowired. Ca permet d'avoir un meilleur controle sur l'injection et de pouvoir utiliser final pour bénéficier de l'immutabilité de nos injections.
Pour le faire (vu qu'on utilise Lombok) tu peux ajouter l'annotation @RequiredArgsConstructor et ensuite tu fais ton injection private final ProductService productService;

2024-11-06 11:41 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/controller/ProductController.java
> +        Product savedProduct = productService.createProduct(product);
Une bonne pratique est d'utiliser les logs pour afficher des informations que l'on pourra suivre pour débugger, surtout en prod.
Pour ça t'as une libraire qui s'appelle Slf4j que tu peux ajouter avec l'annotation @slf4j que tu mets au dessus de ta class puis dans tes controller, tu fais quelques choses de ce style
try {
log.info("POST /auth/register - START");
// La logique de ton controller
} finally {
log.info("POST /auth/register - DONE");
}

Le faire dans les controllers ça sera déjà pas mal mais on peut ajouter des logs où on veut

2024-11-06 11:41 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/controller/ProductController.java
> +        return products.isEmpty() ? new ResponseEntity<>(HttpStatus.NO_CONTENT) : new ResponseEntity<>(products, HttpStatus.OK);
Tu peux faire plus simple. Tu peux juste faire un
return new ResponseEntity<>(products, HttpStatus.OK);
Que la liste soit rempli ou pas, on renvoie un array puis c'est le front qui gère l'affichage du tableau ou du message si c'est vide.
Le code NO_CONTENT est surtout utilisé si ta méthode ne renvoie rien comme les méthodes delete par exemple

2024-11-06 11:41 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/controller/ProductController.java
> +    public ResponseEntity<Product> createProduct(@RequestBody Product product) {
Pour une question de sécurité et d'optimisation, on évite d'utiliser l'entité pour récupérer les data de la requête. Ca expose des champs que l'on veut pas que l'utilisateur est accès. 
Pour régler le problème, on utilise des DTO (data transfer object) qui seront des objets qui nous d'exposer uniquement les champs que l'on veut et avec la dépendances Validation on va pouvoir utiliser des annotations pour forcer l'utilisateur à envoyer les bonnes infos. 
Si tu veux plus d'infos, n'hésites pas à me dire. C'est un peu long à expliquer en commentaire

2024-11-06 11:41 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/controller/ProductController.java
> +        return new ResponseEntity<>(savedProduct, HttpStatus.CREATED);
On utilise aussi des DTO pour le renvoi des informations pour une question de sécurité. On veut éviter d'envoyer à l'utilisateur des informations sensibles qui pourrait être contenu dans l'entity (surtout avec les relations entre différentes entity). On pourrait envoyer sans faire exprès un mot de passe. 
Après avoir créer ta class DTO avec les champs que tu veux envoyer. Pour te faciliter la vie tu vas utiliser un mapper de la dépendance Mapstruct (que tu dois créer) qui te permettra de map donc de changer le type de ton objet avec les champs que tu veux. 
Si t'as besoin de plus d'infos, dis moi

2024-11-06 11:41 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/controller/ProductController.java
> +        try {
T'as pas besoin de faire un try/catch, les gestions des erreurs sont directement gérer par notre GlobalExceptionHandler. Ca nous permet de centraliser toute la gestion d'erreur à un seul endroit et d'être homogène sur le renvoie du format de réponse

2024-11-06 11:41 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/entity/Product.java
> +@Data
Une bonne pratique est d'éviter @Data parce que ça génère tout un tas de méthode qui peuvent causer des problèmes avec JPA à la place on préfère utiliser @Getter et @Setter

2024-11-06 11:41 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/entity/Product.java
> +    @NotNull(message = "Le nom du produit ne peut pas être nul")
Quand t'auras créer ton DTO tu pourras mettre toutes test constraints dans le DTO

2024-11-06 11:41 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/entity/Product.java
Peut être à voir avec tout le monde, mais je pense qu'il est mieux d'utiliser des noms de variables en anglais vu que tes méthodes sont en anglais. Non ?

2024-11-06 11:41 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/service/impl/ProductServiceImpl.java
> +    @Autowired
Utiliser le Constructor injection à la place du @Autowired

2024-11-06 11:41 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/service/impl/ProductServiceImpl.java
> +            String ingredientsAsString = String.join(", ", product.getListeIngredients().split(", "));
Tu peux supprimer cette ligne et utiliser (à la ligne suivante) product.setListeIngredients( product.getListeIngredients());

Parce que là dans ta ligne tu découpes ta string pour ensuite la remettre dans le format initial

2024-11-06 11:41 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/service/impl/ProductServiceImpl.java
> +                .orElseThrow(() -> new RuntimeException("Produit non trouvé avec l'ID : " + id));
Pour avoir plus de contrôle sur nos exceptions et pouvoir les gérer ensuite dans notre GlobalExceptionHandler, on créer des exceptions qu'on va étendre avec RuntimeException

2024-11-07 10:11 UTC, Lisadev84 commented on api/src/main/java/com/marketplace/controller/ProductController.java
ok, la doc api en français ou en anglais ?

2024-11-07 10:15 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/controller/ProductController.java
En anglais vu que c'est une doc qui est destinée pour les dev

2024-11-18 10:45 UTC, Pops47 requested changes
J'ai un souci quand je lance docker compose depuis cette branche, le front et la bdd se lancent mais pas le back, et j'ai cette erreur dans les logs :  

<img width="1068" alt="Capture d’écran 2024-11-18 à 11 43 15" src="https://github.com/user-attachments/assets/3e8b2bc6-19ec-498f-b21d-24783e4a81d8">

2024-12-02 18:58 UTC, JeffreyGbeho requested changes

2024-12-02 18:58 UTC, JeffreyGbeho commented on api/build.gradle
> +	implementation 'jakarta.validation:jakarta.validation-api:3.0.2'
Tu peux supprimer cette dépendance.
Jakarta validation est déjà compris dans le spring boot starter validation

2024-12-02 18:58 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/controller/ProductController.java
> +            if (productDtos.isEmpty()) {
Tu peux supprimer ce block de code.
Il vaut mieux renvoyer un json vide avec un code 200 qu'un code 204. C'est plus cohérent et plus simple à gérer pour le front. 
Le code 204 est plus utilisé quand c'est la seule réponse possible sur la route

2024-12-02 18:58 UTC, JeffreyGbeho commented on api/src/test/java/com/marketplace/ApplicationTests.java
> +	 @Test
Ce test ne fonctionne pas. Je crois que c'est parce qu'on a pas de base de données en test

2024-12-02 18:58 UTC, JeffreyGbeho commented on api/src/test/java/com/marketplace/Service/impl/ProductServiceImplTest.java
> +        static class ProductMatcher implements ArgumentMatcher<Product> {
J'ai pas trop compris l'utilité de cette class. Moyen d'avoir plus d'explications stp ?

2024-12-02 18:58 UTC, JeffreyGbeho commented on api/src/test/java/com/marketplace/controller/ProductControllerTest.java
> +            verify(productService, times(1)).createProduct(any(ProductDto.class));
Dans les tests controllers, ce qui est important de tester c'est l'input et l'output. Toutes les méthodes qui sont appelés pour en arriver à l'output ne sont pas testé, ça permet d'avoir des tests moins rigides. 
On utilise verify plutot pour vérifier des appels à des apis externe ou pour des appels méthodes critiques.
Je pense que tu peux supprimer cette ligne et celles des autres tests du controller.

2024-12-02 18:58 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/service/impl/ProductServiceImpl.java
> +        if (products.isEmpty()) {
Tu peux enlever ce block. Si ton repository ne trouve aucun produit alors ta list sera déjà empty. Du coup avec le return products tu renverras forcément un empty list

2024-12-02 18:58 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/service/impl/ProductServiceImpl.java
> +        return productRepository.findById(id)
Pour gagner en performance et séparer correctement les responsabilités des class, il est préférable de déplacer toute la logique dans ton repository. Par ex : 
@Query("SELECT p FROM Product p WHERE p.id = :id AND p.active = true")
Optional<Product> findByIdAndActive(@Param("id") Long id);

Comme ça dans ton service t'as juste à appeler cette requête et faire un return

2024-12-02 18:58 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/service/impl/ProductServiceImpl.java
> +        if (products.isEmpty()) {
Si la liste des produits est vide alors on renvoie une liste vide. N'avoir aucun résultat n'est pas une erreur.
Si on lève une erreur, ça va renvoyer un code d'erreur au front. Le front pourrait traiter les erreurs avec des toasts mais ici on veut pas afficher un toast mais juste un tableau vide avec un message aucun résultat trouvé (par exemple).
NotFound va plus être utilisé si on essaye d'accéder à une ressource spécifique (comme le getById) et que la ressource n'existe pas

2024-12-02 18:58 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/service/impl/ProductServiceImpl.java
> +        Product product = productRepository.findById(id)
Tu peux faire la suppression en une fois avec deleteById ça fait gagner un appel à la db

2024-12-17 19:59 UTC, JeffreyGbeho requested changes

2024-12-17 19:59 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/controller/ProductController.java
> +    public ResponseEntity<ProductDto> createProduct(@Valid @RequestBody ProductDto productDto) {
{
    "name": "tomate",
    "description": "Regardes mon joli panier de tomates",
    "unitPrice": "2",
    "stockQuantity": 10,
    "minQuantity": 5,
    "stepQuantity": 1,
    "criticalLevel": 5,
    "active": true
}

Envoyant ce payload, j'ai un NullPointerException à du maxQuantity. A voir quelle est la meilleure solution pour le gérer. 
Soit rendre le champs obligatoire dans le payload mais est ce que le producteur connait la quantité max à chaque fois ? Sinon gérer le cas dans le service pour éviter cette exception

2024-12-17 19:59 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/dto/ProductDto.java
> +    @Null(groups = OnCreate.class)
Je peux utiliser toutes les routes sans avoir à l'utiliser. Je pense que tu peux le supprimer et du coup ta class OnCreate aussi

2024-12-17 19:59 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/repository/ProductRepository.java
> +    Optional<Product> findByIdAndActive(@Param("id") Long id);
Commentaire juste à titre d'infos : Tu peux faire findByIdAndActiveIsTrue sans avoir à utiliser @Query ça donnera le même résultat. Mais tu peux laisser comme ça, ça fonctionne aussi

2024-12-17 19:59 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/controller/ProductController.java
> +    public ResponseEntity<List<ProductDto>> getProductsByStatus(@RequestParam Boolean active) {
Si dans ma requête je n'envoie pas le paramètre active, j'ai une erreur 500. Je pense qu'il faudrait faire en sorte que ça renvoie une erreur 400 en indiquant qu'il manque le paramètre.

2024-12-17 19:59 UTC, JeffreyGbeho commented on api/src/test/java/com/marketplace/controller/ProductControllerTest.java
> +class ProductControllerTest {
Il te manque les tests pour le endpoint /status

2024-12-18 11:23 UTC, SayliDev reviewed
L'API répond comme prévu, j'ai testé les différents endpoints (création, récupération, mise à jour, suppression) ainsi que les cas d'erreurs. Mais, lors de la création d'un produit, si le champ `maxQuantity` n'est pas renseigné, aucun message d'erreur (erreur 400) n'est renvoyé alors que le champ devrait être obligatoire ?

2024-12-20 22:10 UTC, JeffreyGbeho approved these changes

2024-12-23 17:26 UTC, merged