17 user account
Pinqo-community/marketplace-backend pull request #53
Opened 2024-11-06 12:10 UTC by JeffreyGbeho

Gestion de l'authentification

- Inscription email/password (avec obligation de donner nom et prénom)
- Connexion email/password
- Refresh token si le access token est expiré
- Connexion/inscription avec son compte google
- Connexion/inscription avec son compte facebook

Les variables d'environnements à créer : 
JWT_SECRET="fEo++duKwfrb7kUw8i+6YSqm7CHHE5RxFtUASvCY+/I="
GOOGLE_CLIENT_ID
GOOGLE_SECRET_CLIENT
FACEBOOK_CLIENT_ID
FACEBOOK_SECRET_CLIENT

Pour google et facebook, il faut créer des apps mais si vous avez la flemme je peux vous donner mes clés pour les tests. N'hésitez pas à demander.

Me reste à faire : 
- Ajouter les tests unitaires
- Définir la route de redirection pour le front pour récupérer les tokens d'access quand on se connecte avec oauth2

2024-11-14 18:41 UTC, SayliDev approved these changes
J'ai testé la connexion, l'inscription OAuth et l'authentification email/password. Tout fonctionne correctement, je récupère bien les access token et refresh token dans les deux cas.

2024-11-15 10:23 UTC, Pops47 commented
L'authentification avec Google fonctionne mais celle avec Facebook me donne cette erreur : 

<img width="250" alt="Capture d’écran 2024-11-15 à 11 21 40" src="https://github.com/user-attachments/assets/69bcc735-e402-42f3-99fb-290f197ceb20">

2024-11-15 11:02 UTC, Pops47 requested changes
J'ai 2 petits problèmes : 
- le bug facebook quand je clique sur le lien (cf screenshot dans les commentaires le la PR)
- la vérification du mot de passe dans le login (cf review) : si j'essaye de me connecter avec un mot de passe invalide, j'obtiens quand même un access-token, ce qui ne devrait pas être le cas.

L'auth Google, le register et le refresh-token fonctionnent très bien :)

2024-11-15 11:02 UTC, Pops47 commented on api/src/main/java/com/marketplace/controller/AuthController.java
> +    }
Il reste du contenu random qu'on pourrait enlever dans "example values" dans Swagger mais je ne vois pas d'où ça vient dans ton code : 

<img width="1019" alt="Capture d’écran 2024-11-15 à 11 34 38" src="https://github.com/user-attachments/assets/ef33e76f-cbb9-4e9d-8b78-84ae19f892cd">

2024-11-15 11:02 UTC, Pops47 commented on api/src/main/java/com/marketplace/controller/AuthController.java
> +    }
Je n'ai pas de vérification du mot de passe pour le login, il manque un bout de logique ici avant de générer les tokens non ?

2024-11-15 11:02 UTC, Pops47 commented on api/src/test/java/com/marketplace/controller/AuthControllerTest.java
Et du coup il faudrait rajouter le test " login_WithInvalidPassword_ShouldReturnBadRequest() "

2024-11-15 11:28 UTC, Lisadev84 reviewed
J'ai testé les fonctionnalités d'authentification avec Postman , récupération des tokens ok. Pour Oauth2, pas de soucis non plus. J'ai laissé quelques commentaires plus pour obtenir des informations. Beaucoup découvert notamment sur oAuth.

2024-11-15 11:28 UTC, Lisadev84 commented on api/src/main/resources/application.yml
> +      secret-key: ${JWT_SECRET}
tu n'externalises pas la durée d'expiration du jwt ? C'est facultatif ?

2024-11-15 11:28 UTC, Lisadev84 commented on api/src/main/java/com/marketplace/security/jwt/JwtService.java
> +    private final long refreshAccessTokenExpiration = 24 * 60 * 60 * 1000;
J'aurais externalisé les valeurs avec une variable dans application.yml

2024-11-15 11:28 UTC, Lisadev84 commented on api/src/main/java/com/marketplace/exception/InvalidTokenException.java
Je vois que tu fais 1 fichier par exception. Est-ce que çà fait partie des bonnes pratiques ? plutôt qu'un fichier qui les rassemble

2024-11-15 11:28 UTC, Lisadev84 commented on api/src/main/java/com/marketplace/model/user/OidcUserInfos.java
Je n'ai pas saisi cette implémentation de UserInfos. (Oauth, et BasicUserInfos ok)

2024-11-16 10:05 UTC, JeffreyGbeho commented on api/src/test/java/com/marketplace/controller/AuthControllerTest.java
J'ai rajouté le test dans le service parce que c'est surtout le service qui doit vérifier si les identifiants sont valides ou pas

2024-11-16 10:30 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/exception/InvalidTokenException.java
Je les regroupe par type d'exception pour que ce soit plus facile quand tu lis le code. Tu sais que l'erreur qui va être levé ça va être un problème de token qui est invalide (dans le cas de InvalidTokenException.java) et pas simplement se concentrer sur le code d'erreur renvoyer. 
Ca permet aussi une plus grande flexibilité dans ton code.
Plus tu groupes, plus ça complexifie le maintien de ton code

2024-11-16 10:45 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/model/user/OidcUserInfos.java
J'ai créé cette interface pour utiliser le polymorphisme. Dans l'application j'ai plusieurs façon de m'authentifier email/password, Google (Oidc), Facebook (Oauth2) qui vont être traités avec des objets différents. Ma problématique c'est que peu importe la façon de m'authentifier je veux créer un utilisateur en db.
Soit je fais des méthodes qui va prendre en paramètre les différents types mais c'est un peu redondant et si je décide de modifier la façon de créer l'utilisateur, je dois le faire dans les trois donc pas très pratique.
Soit je fais une méthode commune qui prend en paramètre tous les informations en type primitif pour créer l'utilisateur. Mais même problème qu'avant si je dois rajouter une information pour la création je suis obligé de le faire dans tous les appels et surtout c'est pas très pratique de devoir faire un appel à une méthode en renseignant 5 paramètres.
Du coup la meilleure solution que j'ai trouvé c'est d'avoir une interface avec les méthodes dont j'ai besoin pour créer mon utilisateur et de faire des classes qui vont implémenter mon interface pour chacun de mes types d'authentification. Maintenant je peux juste faire un appel à une seule méthode avec un seul paramètre et si j'ai besoin de changer ma méthode pour créer mon utilisateur, j'ai juste besoin de changer mon interface.

2024-11-16 10:47 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/model/user/OidcUserInfos.java
Je me suis servi du design pattern strategy, si tu veux faire plus de recherche sur le sujet

2024-11-16 16:21 UTC, Lisadev84 commented on api/src/main/java/com/marketplace/model/user/OidcUserInfos.java
Ok j'ai cherché et mieux compris du coup, merci !

2024-11-16 17:25 UTC, Lisadev84 approved these changes

2024-11-17 13:53 UTC, Pops47 commented
Hello, le register et le login fonctionnent bien, je reçoit bien une erreur si le mot de passe est invalide. 

Par contre, j'ai un autre petit problème sur la route refresh-token : 
Lorsque je donne un refreshToken1, il me renvoie un nouveau acessToken2 et refreshToken2, par contre le RefreshToken1 fonctionne encore si on refait la requête (ça redonne un acessToken" et refreshToken3), alors qu'il devrait être écrasé et que seul le refreshToken2 devrait fonctionner. 

Je sais pas si c'est très clair ^^

Pour la connexion Google, maintenant quand je clique sur le premier lien, ça ne me demande pas d'identifiants et j'obtiens juste un écran blanc dont l'url contient un acces token par contre. Je ne sais pas si c'est le comportement attendu ?
L'url que j'obtiens :
http://localhost:8080/api/v1/auth/oauth?access_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidHlwIjoiQmVhcmVyIiwiZXhwIjoxNzMxODUyMjYzLCJpYXQiOjE3MzE4NTEzNjN9.4-Grf_B64P3zxQF_h2jfnhi_9Rg0z_BXz-XXXJkFhMY&refresh_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidHlwIjoiUmVmcmVzaCIsImV4cCI6MTczMTkzNzc2MywiaWF0IjoxNzMxODUxMzYzfQ.snDafvy68XEbN7p_7Nwh9aM0UuwcU7KrQe7rnLzZC2o

Pour Facebook, j'ai maintenant cet écran et cette url : 
<img width="720" alt="Capture d’écran 2024-11-17 à 14 52 17" src="https://github.com/user-attachments/assets/ce2ba3cb-1570-45a7-b39a-b6e8509b94a3">

Url : https://www.facebook.com/v2.8/dialog/oauth?response_type=code&client_id=484996427253700&scope=public_profile%20email&state=-BW70jEMh_W_Ik9w8_etg0yT1LfKQE4OKC5MIpKLsYA%3D&redirect_uri=http://localhost:8080/api/v1/login/oauth2/code/facebook

Je trouve ça bizarre de devoir avoir un identifiant de développeur pour que ça marche. Nos utilisateurs n'auront pas ça quand ils voudront se connecter à l'appli... Ca devrait juste les envoyer vers la page de connexion Google, ou la page de connexion Facebook non?

2024-11-18 08:37 UTC, Pops47 reviewed
Hello, le register et le login fonctionnent bien, je reçoit bien une erreur si le mot de passe est invalide. 

Par contre, j'ai un autre petit problème sur la route refresh-token : 
Lorsque je donne un refreshToken1, il me renvoie bien un nouveau acessToken2 et refreshToken2. Par contre le RefreshToken1 fonctionne encore si on refait la requête (ça redonne un acessToken3 et refreshToken3), alors qu'il devrait être écrasé et que seul le refreshToken2 devrait fonctionner. 

Je sais pas si c'est très clair ^^

Pour la connexion Google, maintenant quand je clique sur le premier lien, ça ne me demande pas d'identifiants et j'obtiens juste un écran blanc dont l'url contient un acces token par contre. Je ne sais pas si c'est le comportement attendu ?
L'url que j'obtiens :
http://localhost:8080/api/v1/auth/oauth?access_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidHlwIjoiQmVhcmVyIiwiZXhwIjoxNzMxODUyMjYzLCJpYXQiOjE3MzE4NTEzNjN9.4-Grf_B64P3zxQF_h2jfnhi_9Rg0z_BXz-XXXJkFhMY&refresh_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidHlwIjoiUmVmcmVzaCIsImV4cCI6MTczMTkzNzc2MywiaWF0IjoxNzMxODUxMzYzfQ.snDafvy68XEbN7p_7Nwh9aM0UuwcU7KrQe7rnLzZC2o

Pour Facebook, j'ai maintenant cet écran et cette url : 
<img width="720" alt="Capture d’écran 2024-11-17 à 14 52 17" src="https://github.com/user-attachments/assets/ce2ba3cb-1570-45a7-b39a-b6e8509b94a3">

Url : https://www.facebook.com/v2.8/dialog/oauth?response_type=code&client_id=484996427253700&scope=public_profile%20email&state=-BW70jEMh_W_Ik9w8_etg0yT1LfKQE4OKC5MIpKLsYA%3D&redirect_uri=http://localhost:8080/api/v1/login/oauth2/code/facebook

Je trouve ça bizarre de devoir avoir un identifiant de développeur pour que ça marche. Nos utilisateurs n'auront pas ça quand ils voudront se connecter à l'appli... Ca devrait juste les envoyer vers la page de connexion Google, ou la page de connexion Facebook non?

2024-11-20 17:39 UTC, JeffreyGbeho commented
> Hello, le register et le login fonctionnent bien, je reçoit bien une erreur si le mot de passe est invalide.
> 
> Par contre, j'ai un autre petit problème sur la route refresh-token que je n'avais pas vu avant : Lorsque je donne un refreshToken1, il me renvoie bien un nouveau acessToken2 et refreshToken2. Par contre le RefreshToken1 fonctionne encore si on refait la requête (ça redonne un acessToken3 et refreshToken3), alors qu'il devrait être écrasé et que seul le refreshToken2 devrait fonctionner.
> 
> Je sais pas si c'est très clair ^^
> 
> Pour la connexion Google, maintenant quand je clique sur le premier lien, ça ne me demande pas d'identifiants et j'obtiens juste un écran blanc dont l'url contient un acces token par contre. Je ne sais pas si c'est le comportement attendu ? L'url que j'obtiens : http://localhost:8080/api/v1/auth/oauth?access_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidHlwIjoiQmVhcmVyIiwiZXhwIjoxNzMxODUyMjYzLCJpYXQiOjE3MzE4NTEzNjN9.4-Grf_B64P3zxQF_h2jfnhi_9Rg0z_BXz-XXXJkFhMY&refresh_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidHlwIjoiUmVmcmVzaCIsImV4cCI6MTczMTkzNzc2MywiaWF0IjoxNzMxODUxMzYzfQ.snDafvy68XEbN7p_7Nwh9aM0UuwcU7KrQe7rnLzZC2o
> 
> Pour Facebook, j'ai maintenant cet écran et cette url : <img alt="Capture d’écran 2024-11-17 à 14 52 17" width="720" src="https://private-user-images.githubusercontent.com/89612100/386964163-ce2ba3cb-1570-45a7-b39a-b6e8509b94a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMjM2OTMsIm5iZiI6MTczMjEyMzM5MywicGF0aCI6Ii84OTYxMjEwMC8zODY5NjQxNjMtY2UyYmEzY2ItMTU3MC00NWE3LWIzOWEtYjZlODUwOWI5NGEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDE3MjMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNTdiYjE1OTNlYzdiN2I5ZmNkYTJjZmZlODI1YmYxMzE2NmJjM2Q4OTcwZjQ2ZjRiNWE2NmZkYWMzYjJlMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9nxSnFKr3MKihWKl91zWPqGvOPYX4HVE84GKe9eyZPs">
> 
> Url : https://www.facebook.com/v2.8/dialog/oauth?response_type=code&client_id=484996427253700&scope=public_profile%20email&state=-BW70jEMh_W_Ik9w8_etg0yT1LfKQE4OKC5MIpKLsYA%3D&redirect_uri=http://localhost:8080/api/v1/login/oauth2/code/facebook
> 
> Je trouve ça bizarre de devoir avoir un identifiant de développeur pour que ça marche. Nos utilisateurs n'auront pas ça quand ils voudront se connecter à l'appli... Ca devrait juste les envoyer vers la page de connexion Google, ou la page de connexion Facebook non?

Pour la partie refresh token, je vais voir ce que je peux faire pour faire un système qui soit scalable sans avoir à remplir la base de données d'informations "inutiles". Si vous avez des idées, je suis preneur.

Pour google, c'est normal tes identifiants ont été stocké dans les cookies quand tu t'es connecté la première fois. 
Pour facebook, il te manque une configuration dans ton app je pense pour que l'application puisse utilisé toutes les permissions nécessaires.
Il te faut des identifiants de développeur uniquement pour tester tant que ton application n'est pas encore en live. Quand l'application sera en ligne, tout le monde pourra se connecter avec ses identifiants facebook de base.

2024-11-23 15:11 UTC, merged