feat: add products section and product card component in homepage
Pinqo-community/marketplace-backend pull request #61
Opened 2024-11-12 11:49 UTC by SayliDev

## Version: 0.6.0

### Description
Cette PR introduit la section des produits populaires sur la page d'accueil avec les cartes de produit.

### Fonctionnalités
- **Composant ProductCard** :
  - Structure de base et intégration des assets.
  - États de survol et transitions ajoutés pour les interactions.

- **Section des produits populaires** :
  - Intégration d'une grille de produits pour afficher les cartes de manière responsive.
  - Animation des éléments au chargement et sur les interactions grâce à Framer Motion.

### Captures d'écran
![image](https://github.com/user-attachments/assets/ae5112af-3550-476a-9265-74f937b5824e)

> [!NOTE]
> Les cartes peuvent paraître assez espacées entre elles en raison de l'alignement de la grille avec le titre de la section.

2024-11-15 08:54 UTC, Pops47 requested changes
Première tentative de review, j'espère que j'ai bien utilisé le truc ^^
N'hésites pas si tu as des questions ou que t'es pas d'accord avec moi !

2024-11-15 08:54 UTC, Pops47 commented on client/src/components/ProductCard/ProductCard.module.scss
> +      height: inherit;
C'est déja le comportement par défaut de prendre la taille du parent il me semble, du coup cette ligne doit pouvoir s'enlever.

2024-11-15 08:54 UTC, Pops47 commented on client/src/components/ProductCard/ProductCard.tsx
Je me demande s'il n'y a pas un moyen de simplifier la logique au niveau des states (currentQuantity et displayedQuantity) pour n'en a voir qu'un seul. J'ai pas creusé mais GPT me dit que c'est possible de faire avec motion.span pour l'animation, ça te parle ?

2024-11-15 08:54 UTC, Pops47 commented on client/src/pages/HomePage/HomePage.tsx
Pour organiser le code et alléger ce ficher, tu peux mettre ta liste de products dans un fichier à part (dans un dossier fakers par exemple). Tu peux également créer des fonctions (dans un dossier api par exemple) du style "getProducts" qui va pour l'instant juste récupérer ton faker, et que l'on modifiera ensuite quand on fera le cablage pour qu'elle récupère les données du back. 

Et dans ta page tu fais un products = getProducts(), soit dans un useEffect, soit avec une bibliothèque comme ReactQuery, je sais pas si tu connais ?

2024-11-15 08:54 UTC, Pops47 commented on client/src/pages/HomePage/HomePage.module.scss
Est-ce qu'on rajouterais pas un peu de marge horizontale sur les grands écrans pour le MainLayout ? Je trouve que ça fait un peu bizarre d'avoir les produits et la carte sur toute la largeur.

2024-11-15 16:51 UTC, SayliDev commented on client/src/components/ProductCard/ProductCard.module.scss
> +      height: inherit;
> C'est déja le comportement par défaut de prendre la taille du parent il me semble, du coup cette ligne doit pouvoir s'enlever.

Par défaut, l'image s'ajuste à son propre contenu, par contre, tu me fais rappeler que c'est beaucoup plus judicieux d'utiliser `height: 100%` que `height: inherit`

2024-11-15 17:08 UTC, SayliDev commented on client/src/components/ProductCard/ProductCard.tsx
En effet, ça permet d'utiliser uniquement un seul état et en plus ça simplifie le code, même plus besoin du useEffect, bien vu !

2024-11-15 17:48 UTC, SayliDev commented on client/src/pages/HomePage/HomePage.module.scss
J'ai pas trop compris 😅

2024-11-16 10:11 UTC, SayliDev commented on client/src/pages/HomePage/HomePage.tsx
C'est vrai que ce sera déjà chose faite pour plus tard, je pense utiliser RTK Query, car c'est déjà dans Redux

2024-11-17 15:58 UTC, JeffreyGbeho requested changes

2024-11-17 15:58 UTC, JeffreyGbeho commented on client/src/components/ProductCard/ProductCard.module.scss
> +  width: 305px;
Le problème avec les tailles fixes, c'est qu'en fonction de la taille de l'écran ça fait résultat bizarre et c'est plus difficile à maintenir si tu dois faire des breakpoints pour toutes les tailles d'écran.
Exemple de résultat : 
![{5993306D-02A7-4B9B-B761-DE739FA3BED2}](https://github.com/user-attachments/assets/ddf2b73d-995a-4498-9146-e4212e684669)

Je pense que le mieux c'est de gérais la taille des boxes avec une grid dans la class productsGrid de la homepage (cf commentaire dans la homepage)

2024-11-17 15:58 UTC, JeffreyGbeho commented on client/src/components/ProductCard/ProductCard.module.scss
> +    width: 265px;
Même problème que sur le container. Enlever la width et la height
Une bonne alternative, c'est de rajouter la propriété aspect-ratio: 1/1 dans ton img ce qui te donnera une image tout le temps carré peu importe la taille de ton container

2024-11-17 15:58 UTC, JeffreyGbeho commented on client/src/components/ProductCard/ProductCard.module.scss
> +    .header {
J'alignerais le note sur la la même ligne que le titre au lieu de les centrer
![{A8E926FF-38AC-4C3E-AD99-B219BF6ED4A4}](https://github.com/user-attachments/assets/d38e9c89-66a6-4b18-9cef-de66608e68d7)

Je sais ce que tout le monde en pense ?

2024-11-17 15:58 UTC, JeffreyGbeho commented on client/src/components/ProductCard/ProductCard.tsx
> +              <motion.span
Est ce qu'on fait en sorte que l'utilisateur puisse entrer la quantité qu'il veut à la main sans avoir à cliquer sur le plus ou le moins ? @SayliDev @Pops47 @Lisadev84

2024-11-17 15:58 UTC, JeffreyGbeho commented on client/src/pages/HomePage/HomePage.module.scss
> +    .titleContainer {
![{5DD38631-A403-46F1-8693-1E0BBCADA160}](https://github.com/user-attachments/assets/d900d8f8-37e8-4c36-af5b-40fa1084153b)

Je trouve un peu bizarre la disposition des éléments du titre en version mobile. Est ce qu'on les garderait pas de la même façon que sur la version desktop, l'un à coté de l'autre ?

2024-11-17 15:58 UTC, JeffreyGbeho commented on client/src/pages/HomePage/HomePage.module.scss
> +      display: flex;
Par rapport à ce que je te disais dans ta class .productCard avec les tailles fixes.
`
display: grid;
gap: 20px;
grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));`

tout le reste tu peux le supprimer

Ca te permettra de mieux gérer l'espacement vertical et horizontal et c'est ton grid template columns qui va gérer la taille de tes éléments de façon dynamique. Il remplira la ligne avec des éléments qui font au minimum 300px sinon il les met sur une autre ligne

2024-11-17 19:25 UTC, SayliDev commented on client/src/pages/HomePage/HomePage.module.scss
> +      display: flex;
Ok ça marche, j'ai tendance à mettre flex-wrap mais en grid c'est vrai que c'est beaucoup mieux

2024-11-18 10:06 UTC, Pops47 commented on client/src/pages/HomePage/HomePage.module.scss
La marge est bonne maintenant, je ne sais pas trop si c'est moi qui avait un bug ou si ça a changé avec le grid peut-être..Bref, c'est tout bon !

2024-11-18 10:12 UTC, Pops47 reviewed
Pour tout le reste c'est bon pour moi :)

2024-11-18 10:12 UTC, Pops47 commented on client/src/pages/HomePage/HomePage.tsx
> +          <div className={styles.mapWrapper}>
Il manque un peu de marge sous ce titre en version mobile. On pourrait le centrer aussi éventuellement ?

2024-11-18 10:13 UTC, Pops47 approved these changes

2024-11-18 10:47 UTC, SayliDev commented on client/src/pages/HomePage/HomePage.tsx
> +          <div className={styles.mapWrapper}>
Ah oui, c'est normal. Ça concerne pas cette PR, mais ç'a été corrigé. Il me reste juste à merger la PR 0.5.1

2024-11-18 16:21 UTC, Lisadev84 commented
Pour ma part, j'ai des photos de produits qui ne sont pas de tailles identiques sur les fiches produits, un panier qui pourrait être remonté de manière à être aligné avec le tableau quantité.  Le titre "Pomme de terre bio" n'est pas espacé avec la note contrairement aux autres  titres.

2024-11-18 18:49 UTC, SayliDev commented
> Pour ma part, j'ai des photos de produits qui ne sont pas de tailles identiques sur les fiches produits, un panier qui pourrait être remonté de manière à être aligné avec le tableau quantité. Le titre "Pomme de terre bio" n'est pas espacé avec la note contrairement aux autres titres.

Merci, c'est corrigé. En fait, tout ce que tu décris vient de `aspect-ratio: 1/1` qui devait être défini non seulement sur le conteneur, mais aussi directement sur la balise <img> pour éviter ce bug, uniquement visible sur Chrome.

2024-11-19 07:50 UTC, Lisadev84 approved these changes
Tout est rentré dans l'ordre. J'ai testé sur différents navigateurs.

2024-11-19 07:50 UTC, Lisadev84 commented on client/src/components/ProductCard/ProductCard.tsx
> +              <img src={bag} alt="bag" className={styles.bagIcon} />
Cet icône pourrait être centré avec la quantité (en hauteur)

2024-11-20 17:11 UTC, JeffreyGbeho commented on client/src/components/ProductCard/ProductCard.module.scss
> +  width: 305px;
Tu peux supprimer la propriété width vu que tu le gères dans ton container. Ca évitera des problèmes si on réutilise le component ailleurs. 
Après ça c'est bon pour moi tu peux merge

2024-11-20 18:09 UTC, SayliDev commented on client/src/components/ProductCard/ProductCard.module.scss
> +  width: 305px;
Ça marche, c'est corrigé👍

2024-11-21 09:11 UTC, merged