feat(Category): Add category section with slider, animations, and API integration
Pinqo-community/marketplace-backend pull request #64
Opened 2024-11-24 15:41 UTC by SayliDev

## Version: 0.7.0

### Description
Cette PR introduit la section des catégories sur la page d'accueil en utilisant SwiperJS.

### Fonctionnalités
- **Composant Catégorie** : Ajout de la section des catégories, incluant le slider et l'animation des cartes ainsi que les boutons de navigation.

- **API** : Intégration de la récupération des catégories via RTK Query avec la création de `categoriesApi` pour gérer les requêtes.

### Dépendances ajoutées
  - `swiper 11.1.15`

2024-11-25 18:07 UTC, JeffreyGbeho requested changes
Tester des catégories avec des noms qui font plus d'une ligne, ca change la hauteur et du coup tous les éléments n'ont plus la même hauteur, ca fait un affichage un peu bizarre

2024-11-25 18:07 UTC, JeffreyGbeho commented on client/src/components/CategoryCard/CategoryCard.module.scss
> +  width: 196px;
Eviter les tailles fixes. Pour avoir ton component qui soit réutilisable dans d'autres contextes et pour que le gap entre les éléments sur tous les écrans soit le même.
Je supprimerai la propriété width et height (si t'as un nom de catégorie qui fait plus d'une ligne, l'affichage est bizarre)

2024-11-25 18:07 UTC, JeffreyGbeho commented on client/src/components/CategoryCard/CategoryCard.module.scss
> +    width: 169px;
Tu peux enlever les tailles fixes (width et height) et utiliser aspect-ratio: 1/1

2024-11-25 18:07 UTC, JeffreyGbeho commented on client/src/pages/HomePage/HomePage.module.scss
> +  .categoryContainer {
Cette class n'a pas vraiment d'effet sur ton affichage parce que swiper génère des containers à l'intérieur du coup tu peux supprimer

2024-11-25 18:07 UTC, JeffreyGbeho commented on client/src/pages/HomePage/HomePage.tsx
> +              320: { slidesPerView: 1 },
Je mettrais 2 pour l'affichage téléphone vu que les catégories n'ont pas beaucoup d'informations. Ca rend mieux, je sais pas que t'en penses

2024-11-25 20:03 UTC, SayliDev commented on client/src/components/CategoryCard/CategoryCard.module.scss
> +  width: 196px;
> (si t'as un nom de catégorie qui fait plus d'une ligne, l'affichage est bizarre)

J'ai fait une petite fonction qui applique une taille de texte différente en fonction de la longueur de caractères, je sais pas si ça te convient de cette façon : 
![image](https://github.com/user-attachments/assets/6fb0b5a9-0226-4e88-b7d0-e0a6640390d5)

2024-11-26 17:18 UTC, JeffreyGbeho commented on client/src/components/CategoryCard/CategoryCard.module.scss
> +  width: 196px;
Yep pourquoi pas, ça me va très bien

2024-11-26 17:44 UTC, SayliDev commented on client/src/pages/HomePage/HomePage.tsx
> +              320: { slidesPerView: 1 },
> Je mettrais 2 pour l'affichage téléphone vu que les catégories n'ont pas beaucoup d'informations. Ca rend mieux, je sais pas que t'en penses

Ok, de 580 à 420 je passe à deux, mais en dessous de 420 je suis obligé de passé à 1

2024-12-02 13:27 UTC, Lisadev84 approved these changes
Tout est ok pour moi.

2024-12-02 20:24 UTC, JeffreyGbeho approved these changes
Faire un rebase avant de merge pour corriger les conflits

2024-12-02 22:35 UTC, merged