feat: Add buyer/producer cards in homepage
Pinqo-community/marketplace-backend pull request #65
Opened 2024-11-28 17:29 UTC by SayliDev

## Version: 0.8.0

### Description
Ajout de la section des cartes `BuyerProducerCard` avec animation d'apparition (image, titre, description, bouton).

### Fonctionnalités
- Affichage des cartes pour acheteurs et producteurs avec des données personnalisées via props.
- Animation de l'apparition au scroll avec Framer Motion.
- Mise en page adaptée pour tous les écrans.

### Aperçu 
![image](https://github.com/user-attachments/assets/d39dcd27-edf5-4f10-956f-2aa9fc402d85)

2024-12-04 21:02 UTC, JeffreyGbeho requested changes
![{E66CA96A-E882-4753-ADC2-0DF2F6AF7CF0}](https://github.com/user-attachments/assets/a0cc5642-923f-4b20-8a8f-b891fd190bd2)
Y'a des deprecated dans les logs, je sais pas si c'est une dépendance qui fait ou pas.

2024-12-04 21:02 UTC, JeffreyGbeho commented on client/src/components/BuyerProducer/BuyerProducer.module.scss
> +
Entre les breakpoints 480px et 1200px, les containers ne font pas toutes la largeur. C'est voulu ?
Ca me fait surtout bizarre en dessous en dessous du breakpoint 768px

2024-12-05 21:00 UTC, SayliDev commented on client/src/components/BuyerProducer/BuyerProducer.module.scss
> +
> Entre les breakpoints 480px et 1200px, les containers ne font pas toutes la largeur. C'est voulu ? Ca me fait surtout bizarre en dessous en dessous du breakpoint 768px

Tu penses que c'est mieux si ça prend toute la largeur ?

![image](https://github.com/user-attachments/assets/5925a525-d99d-40d8-925a-f9e2e31a5f3a)
## Actuelle :
![image](https://github.com/user-attachments/assets/a0c0cb2e-4c62-4068-9a82-e3e94c19f201)

2024-12-06 16:48 UTC, JeffreyGbeho commented on client/src/components/BuyerProducer/BuyerProducer.module.scss
> +
Je trouve plus cohérent quand ça prend toute la largeur, surtout par rapport à la mise en page des autres éléments autour. 
Après je sais pas ce qu'en pense les autres

2024-12-09 18:26 UTC, merged