feat(testimonial): Integrate "Testimonial" section on the homepage with slider and pagination
Pinqo-community/marketplace-backend pull request #71
Opened 2024-12-05 16:15 UTC by SayliDev

## Version : 0.8.0

### Description :
- Ajout de la dernière section "Testimonials" sur la page d'accueil.
- Intégration des avis récupérés via RTK Query.
- Mise en place de la pagination pour les avis.
- Ajout des boutons de navigation du slider.
- Création d'un composant de section pour le slider, réutilisant la même structure que celle utilisée pour le slider de catégories.

2024-12-13 10:49 UTC, Lisadev84 reviewed
En supprimant l' import "react-leaflet-markercluster/dist/styles.min.css"; dans src/components/Map, la homepage se charge correctement.

2024-12-13 10:49 UTC, Lisadev84 commented on client/src/types/Slider.ts
> +  renderItem: (item: T) => JSX.Element;
j'ai cet avertissement  pour JSX dans Intellij: Deprecated symbol used, consult docs for better alternative

2024-12-13 10:49 UTC, Lisadev84 commented on client/vite.config.ts
> +import path from "path";
TS2307: Cannot find module 'path' or its corresponding type declarations.

2024-12-13 10:49 UTC, Lisadev84 commented on client/vite.config.ts
J'ai 2 erreurs dans ce fichier mais sans impact sur le chargement de la homepage

2024-12-13 10:49 UTC, Lisadev84 commented on client/vite.config.ts
> +      "@": path.resolve(__dirname, "./src"),
TS2304: Cannot find name '__dirname'.

2024-12-13 18:04 UTC, SayliDev commented on client/vite.config.ts
> J'ai 2 erreurs dans ce fichier mais sans impact sur le chargement de la homepage

Ok c'est réglé, la dépendance n'était pas dans le fichier package.json, donc docker ne l'a pas installée

2024-12-16 14:43 UTC, Lisadev84 approved these changes, later dismissed

2024-12-16 15:54 UTC, Lisadev84 reviewed
J'ai ces 3 erreurs sous docker ! 
![Capture d’écran 2024-12-16 165245](https://github.com/user-attachments/assets/40ddc2ad-c517-4f57-aab5-b3f48193138f)

2024-12-16 18:56 UTC, SayliDev commented
> J'ai ces 3 erreurs sous docker mais la page se charge. ![Capture d’écran 2024-12-16 165245](https://private-user-images.githubusercontent.com/118628266/396164239-40ddc2ad-c517-4f57-aab5-b3f48193138f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNjkyODEsIm5iZiI6MTczNDM2ODk4MSwicGF0aCI6Ii8xMTg2MjgyNjYvMzk2MTY0MjM5LTQwZGRjMmFkLWM1MTctNGY1Ny1hYWI1LWIzZjQ4MTkzMTM4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQxNzA5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWU4OGIyY2RlNTA5NDcyYzk1YTc3ZjEwMmI5MWI2YjY3NjMzZDJmYzI1NzEzYTE3ZGUxZDQyZmY1ZTc0NDkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fJuL0B6tEnOJU9-sx6eD9I7hsXi3I3tdNRFnra1DPXk)

Pour la première erreur c'est réglé, pour les deux autres (concernant `tsconfig.app.json`), j'obtiens aucun de ces messages
Tu peux me confirmer si tu les vois toujours sur la version 0.12.0F ? (Réf : #86)

2024-12-17 08:13 UTC, Lisadev84 commented
Après correctif , tout est ok. L'erreur tsconfig app.json n'apparait qu'en lien avec cet import 
import "react-leaflet-markercluster/dist/styles.min.css"; 
Une fois commenté, tout tourne correctement, juste l'erreur reste affichée dans la console çà m'a induit en erreur.

2024-12-17 08:14 UTC, Lisadev84 approved these changes

2024-12-17 20:52 UTC, JeffreyGbeho requested changes

2024-12-17 20:52 UTC, JeffreyGbeho commented on client/src/components/Testimonials/TestimonialCard.module.scss
> +  width: 413px;
Mettre la width à 100%. C'est ton container qui va gérer l'espace

2024-12-17 20:52 UTC, JeffreyGbeho commented on client/src/components/Testimonials/TestimonialCard.module.scss
> +  height: 246px;
Si on a un texte long, on a un problème d'affichage

2024-12-17 20:52 UTC, JeffreyGbeho commented on client/src/pages/HomePage/HomePage.tsx
> +          breakpoints={{
`breakpoints={{
            0: { slidesPerView: 1 },
            768: { slidesPerView: 2 },
            1200: { slidesPerView: 3 }
          }}`

J'aurais plutôt fait un découpage comme ça. Ca permet d'avoir des cartes pas trop grande ou avec trop d'espaces entre, tout en gardant une bonne lisibilité

2024-12-18 17:07 UTC, SayliDev commented on client/src/pages/HomePage/HomePage.tsx
> +          breakpoints={{
En effet, je trouve que c'est mieux aussi 👍

2024-12-20 22:20 UTC, JeffreyGbeho approved these changes

2024-12-21 12:35 UTC, merged