78 crud label
Pinqo-community/marketplace-backend pull request #92
Opened 2024-12-28 16:48 UTC by Lisadev84

### Implémentation du CRUD pour les Labels avec tests

Cette PR implémente le CRUD pour la gestion des Labels. Cela permettra de manipuler les entités Label nécessaires à l'organisation des produits sur la plateforme.

- Création de l'entité `Label` et `Dto`
- Création des endpoints CRUD dans `LabelController`
- Ajout des méthodes dans `LabelService` et `LabelRepository`
- Écriture des tests pour chaque endpoint  du contrôleur (`LabelControllerTest`)
- Tests unitaires pour les méthodes du service (`LabelServiceTest`)
- Gestion des exceptions spécifiques via le `GlobalExceptionHandler`

2025-01-06 17:46 UTC, JeffreyGbeho requested changes
Quand je lance les tests, j'ai ces erreurs. Je sais pas si ça le fait aussi de ton côté
![{66732E7F-0AAA-485D-BE5B-A8BC76B20A62}](https://github.com/user-attachments/assets/0e5408c5-52c4-4c06-8c6b-7e25ed8560f5)

2025-01-06 17:46 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/configuration/SecurityConfig.java
> +            "/labels/**"
Toutes les méthodes ne doivent pas être accessible par tous les utilisateurs. Le POST, PUT, DELETE doivent être utilisable uniquement par le rôle ADMIN

2025-01-06 17:46 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<ExceptionResponse> handleAlreadyExistsException(AlreadyExistsException ex, WebRequest request) {
Il y a déjà une méthode qui a le même comportement du coup tu peux ajouter la class de ton exception en plus dans l'handler et supprimer cette méthode

2025-01-06 17:46 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/repository/LabelRepository.java
> +    List<Label> findAll();
findAll est déjà implémenté par défaut quand tu étends la class JpaRepository. Tu peux supprimer cette méthode pour éviter la duplication de code

2025-01-06 17:46 UTC, JeffreyGbeho commented on api/src/main/java/com/marketplace/service/impl/LabelServiceImpl.java
> +        if (labelDto.getName() == null) {
Ce check est pas forcément utile vu que dans le dto il y a les annotations de validation. Au pire tu peux rajouter @NotNull. Je sais pas si @NotBlank gère le cas

2025-01-10 12:10 UTC, Lisadev84 commented on api/src/main/java/com/marketplace/service/impl/LabelServiceImpl.java
> +        if (labelDto.getName() == null) {
Il n'est effectivement pas utile, j'ai oublié de le retirer après avoir ajouter @NotBlank sur le champs "name" dans le DTO. Il est plus complet que @NotNull car il gère le vide et les espaces blancs mais que pour le type String

2025-01-10 17:25 UTC, Lisadev84 reviewed
Modifications apportées

2025-01-10 17:25 UTC, Lisadev84 commented on api/src/main/java/com/marketplace/service/impl/LabelServiceImpl.java
> +        if (labelDto.getName() == null) {
J'ai supprimé le test dans LabelServiceImplTest et ajouté un test dans LabelcontrollerTest

2025-01-11 14:51 UTC, SayliDev requested changes
J'ai testé tous les endpoints CRUD pour les Labels, tout fonctionne parfaitement (création, récupération, mise à jour, suppression, et gestion des erreurs).

Par contre, au moment du build, tous les containers se construisent correctement sauf backend-tests, où j'ai une erreur de verrouillage de cache Gradle (voir capture d'écran). Je suis pas sûr si c'est lié à ma configuration, peut-être une instance de Gradle en cours d'exécution ?

![image](https://github.com/user-attachments/assets/3f84334d-8c35-42e5-9f7f-226b23176d1c)

2025-01-13 12:17 UTC, merged