feat(location): add LocationPopup component with geolocation and suggestions
Pinqo-community/marketplace-backend pull request #93
Opened 2024-12-30 20:45 UTC by SayliDev

## Description :
Ajout de la popup de localisation avec détection de la géolocalisation, suggestions d'adresse et gestion des localisations récentes.

## Fonctionnalités principales :

### Popup de localisation :
- Utilisation du composant **BasePopup** pour la présentation.
- Détection de la géolocalisation avec le bouton **"Locate Me"** utilisant l'API de géolocalisation du navigateur.
- Suggestions dynamiques pour les adresses avec validation.
- Gestion des localisations récentes affichées directement dans la popup.

### Gestion de l'état avec Redux :
- Slice Redux pour suivre la localisation de l'utilisateur, les suggestions, et l'état d'ouverture de la popup.
- Cache des localisations récentes et de la localisation actuelle dans **localStorage** pour persistance.

### Tests :

#### Tests unitaires avec Jest :
- Validation des actions Redux (ajout, suppression, mise à jour des localisations).
- Tests des fonctions clés de la popup, comme la gestion des erreurs de géolocalisation.

#### Tests E2E avec Cypress :
- Vérification des interactions utilisateur, détection automatique de la localisation et la sélection d'une suggestion.
- Validation de l'affichage et du comportement de la popup sur divers scénarios.

> [!NOTE]  
> Aucune clé d'API n'est requise. La géolocalisation utilise les services suivants :
> [Nominatim d'OpenStreetMap](https://nominatim.openstreetmap.org)
> [API Adresse de la Data.gouv.fr](https://adresse.data.gouv.fr/api-doc/adresse)

## Version du front : 0.13.0

2025-01-06 18:18 UTC, JeffreyGbeho requested changes
J'ai fait une review rapide mais pas trop lu le code encore. Je le ferais quand j'aurais plus de temps

2025-01-06 18:18 UTC, JeffreyGbeho commented on client/src/components/LocationPopup/LocationPopup.tsx
Je pense que la popup devrait être affiché dès le début si l'utilisateur n'a pas encore de localisation enregistré et l'utilisateur ne doit pas pouvoir fermer la popup jusqu'à qu'une localisation soit sélectionné

2025-01-06 18:18 UTC, JeffreyGbeho commented on client/src/components/LocationPopup/LocationPopup.tsx
![{245D6E93-C337-4A87-9CD0-86518196FD3D}](https://github.com/user-attachments/assets/ef135f1f-06a5-4b2a-8c9b-00c0921bbe00)

Quand j'utilise la détection de ma localisation, j'ai un undefined avant la ville. Je sais pas trop d'où ça peut venir. Dis moi si t'as besoin de plus d'informations pour debug

2025-01-07 16:57 UTC, SayliDev commented on client/src/components/LocationPopup/LocationPopup.tsx
Ok ça marche 👍

2025-01-07 17:56 UTC, SayliDev commented on client/src/components/LocationPopup/LocationPopup.tsx
> ![{245D6E93-C337-4A87-9CD0-86518196FD3D}](https://private-user-images.githubusercontent.com/150350006/400512422-ef135f1f-06a5-4b2a-8c9b-00c0921bbe00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYyNjgzMDgsIm5iZiI6MTczNjI2ODAwOCwicGF0aCI6Ii8xNTAzNTAwMDYvNDAwNTEyNDIyLWVmMTM1ZjFmLTA2YTUtNGIyYS04YzliLTAwYzA5MjFiYmUwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwN1QxNjQwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjI4MjRjZjZmYmJmOTdiMGE2NGU5MGU5NjBjNGMzZjEyODRkNzcwM2E3ZDliMzQ4MGZlMjc4OTgyNWFlZTFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Zgi_ibte2NObXfMSCNWIxPnalhT2ci4r2b78qV1l1uM)
> 
> Quand j'utilise la détection de ma localisation, j'ai un undefined avant la ville. Je sais pas trop d'où ça peut venir. Dis moi si t'as besoin de plus d'informations pour debug

Tu vois un message d'erreur dans la console ? Est-ce que la carte te place bien sur ta localisation exacte ? C'est peut-être lié à l'API de géolocalisation ou à la façon dont l'adresse est récupérée dans le hook, je vais voir ce que je peux faire

2025-01-13 10:08 UTC, Lisadev84 reviewed
Le build du projet fonctionne, juste un problème avec ESLint, ce qui a un impact sur la majorité des fichiers. Sinon, la pop-pup est présente et fonctionnelle. 
J'ai remarqué en revanche que l'on pouvait parcourir l'ensemble de la carte sans limitation aux 50kms.

2025-01-13 10:08 UTC, Lisadev84 commented on client/cypress.config.ts
J'ai une erreur sur ce fichier avec l'affichage de ce message :
ESLint: SyntaxError: Cannot use import statement outside a module 

et celui-ci en console : 
TS2307: Cannot find module 'cypress' or its corresponding type declarations.

2025-01-13 10:08 UTC, Lisadev84 commented on client/cypress/e2e/locationPopup.spec.cy.ts
même problème avec ce fichier du coup.

2025-01-13 17:50 UTC, SayliDev commented on client/cypress.config.ts
J'ai pas détecté d'erreurs de mon côté. Tu pourrais tester de faire un npm install directement en local, sans Docker, pour voir si ça résout l'erreur ?

2025-01-13 17:56 UTC, SayliDev commented
> Le build du projet fonctionne, juste un problème avec ESLint, ce qui a un impact sur la majorité des fichiers. Sinon, la pop-pup est présente et fonctionnelle. J'ai remarqué en revanche que l'on pouvait parcourir l'ensemble de la carte sans limitation aux 50kms.

Effectivement, la limitation des 50 km n'était pas appliquée j'avais refactorisé la fonction dans un fichier utils, mais elle n'était pas utilisée. C'est maintenant corrigé et fonctionnel

2025-01-14 15:56 UTC, Lisadev84 commented on client/cypress.config.ts
C'était identique avec npm install via /client. Problème résolu avec tes derniers commits. (ajout du "type": "module" dans le package.json)

2025-01-14 17:43 UTC, SayliDev commented on client/cypress.config.ts
Ok tant mieux si ça a résolu le problème ! Par contre, ça a causé quelques soucis sur la CI/CD avec GitHub Actions, donc je vais creuser pour stabiliser tout ça

2025-01-14 19:36 UTC, SayliDev commented on client/cypress.config.ts
> Ok tant mieux si ça a résolu le problème ! Par contre, ça a causé quelques soucis sur la CI/CD avec GitHub Actions, donc je vais creuser pour stabiliser tout ça

Problème avec la CI/CD réglé (enfin)

2025-01-15 10:45 UTC, Lisadev84 approved these changes

2025-01-31 21:34 UTC, JeffreyGbeho approved these changes

2025-02-02 18:59 UTC, merged